# This file is used to configure the application properties.
spring:
  application:
    name: ai-starter
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
#         model: glm4
          temperature: 0.7